language: node_js
node_js:
- '8'
sudo: false
branches:
  except:
  - gh-pages
install:
- npm install
script:
- npm test
- npm run-script updatedb license_key=$LICENSE_KEY
- npm run-script updatedb force license_key=$LICENSE_KEY
# Reads the $LICENSE_KEY
- npm run-script updatedb
- npm run-script updatedb force
env:
  global:
    secure: Vkd7N3iC3uYOQJiYjdeHUZHlqk1p10WLtr19DW04LFAqz4DkZAehuHJxgXxdlzd7iZbyiAjEQqIAOuO/JbW46oRQTRDAZfz6XAp0h1VC81zP7mJFtAGiXD9rnZDmG4R+2rshIB4JhtC2P5DHzO7PnlvCd8ebg2CtOFpz/QzuPS8zVFahDoj7+1bDOb48MTMkf54+XXVnkdko39lA4arnxSwAORxW5e7VyJLG6gVZuGIdAz6d5QPKoBvKZ3P7812pIpYtIRXpvOLqLznlJ7iIZ1nNU6DmQkqyyJOZqLSO5dtCjzNm6TsVDsPIWib5N8Du2kzNw93X+AhFJIz/nErY8rbrpeH++Ui39JI/QnkJlDFQjRu0VbGtko1V6SPz0Jh8J2eARQiye/NX2YIPOIsPzXb6bsgTr+dCVJiNGms0E/3l4Klj7z1EHVGcCwB33WVUW8X294qp2uBMVcJGn1ID5/erl82MZ6DMWkVJ95/gteGxKBboTVVcAmoV1BrGNyDqtDXBi3pX786kg6j2HEl9o8KctoMD+/cQ2iPVRk96gPkZnZontpVsI9B4FRv6n6xroIGGPqgEddyG9WG3Io3vqyO2doNg8hYXrutacu9fU2tLOJqh1dH9QnTxYh4hM0OOX5bs8j4598N+18wIWO/CMs8hioOCGO9UBl4w+0smH3I=
